services:
  - type: web
    name: capx-stock-portfolio-backend
    env: docker
    buildCommand: "docker build -t capx-stock-portfolio-backend ."
    startCommand: "docker run -p 8080:8080 capx-stock-portfolio-backend"
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://vittalkatwe:vittalkatwe@cautious.rh2qklo.mongodb.net/stockportfolio?retryWrites=true&w=majority
